name: Dynamic Values Workflow

on:
  push:
    branches:
      - main

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: Set Dynamic Variables
        id: set_vars
        run: |
          # Use a script or command to generate dynamic values
          DYNAMIC_LIST=$(generate_dynamic_list.sh)
          echo "DYNAMIC_LIST=${DYNAMIC_LIST}" >> $GITHUB_ENV
        shell: bash

      - name: Show Dynamic Values
        run: |
          # Access the dynamic values using the GitHub Actions context
          echo "Dynamic List: ${{ env.DYNAMIC_LIST }}"
